# Základy hlubokého učení a neuronových sítí

## Co je hluboké učení a kde se používá

Hluboké učení je podmnožinou strojového učení, která se zaměřuje na modely neuronových sítí s více vrstvami. Tyto modely jsou schopny učit se reprezentace dat na různých úrovních abstrakce, což umožňuje řešit složité úlohy, jako je rozpoznávání obrazu, zpracování přirozeného jazyka, a mnoho dalších.

## Architektura neuronových sítí

Neuronové sítě se skládají z následujících vrstev:
- **Vstupní vrstva**: Přijímá vstupní data.
- **Skryté vrstvy**: Provádí výpočty a transformace dat.
- **Výstupní vrstva**: Produkuje výstup modelu.

### Důležité pojmy
- **Tensor**: Vícedimenzionální pole, které je základním datovým typem v hlubokém učení.
- **Váhy (weights)**: Parametry modelu, které se učí během tréninku.
- **Bias**: Posun, který se přidává k výpočtu neuronů.
- **Logit**: Výstup neuronové sítě před aplikací aktivační funkce.

## Aktivace, ztrátové funkce, zpětná propagace

### Aktivace
Aktivační funkce transformuje výstup neuronů. Příklady aktivačních funkcí:
- **ReLU (Rectified Linear Unit)**: `ReLU(x) = max(0, x)`
- **Sigmoid**: `Sigmoid(x) = 1 / (1 + exp(-x))`

### Ztrátové funkce
Ztrátová funkce měří chybu modelu. Příklady ztrátových funkcí:
- **MSE (Mean Squared Error)**: `MSE(y, y_pred) = mean((y - y_pred)^2)`
- **Cross-Entropy Loss**: Používá se pro klasifikační úlohy.

### Zpětná propagace
Zpětná propagace je algoritmus pro optimalizaci váh neuronové sítě. Skládá se z následujících kroků:
1. Výpočet ztráty.
2. Výpočet gradientů ztráty vzhledem k váhám.
3. Aktualizace váh pomocí gradient descent.

## Praktická ukázka v PyTorch

### 1. Import knihoven


In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset
import numpy as np
import pandas as pd

In [3]:
# Ukázková tabulková data
data = {
    'Feature1': [10, 20, 30, 40, 50],
    'Feature2': [5, 15, 25, 35, 45],
    'Feature3': [100, 200, 300, 400, 500]
}

# Vytvoření DataFrame
df = pd.DataFrame(data)

# Převedení DataFrame na NumPy pole
numpy_data = df.values

# Převedení NumPy pole na PyTorch tensor
tensor_data = torch.tensor(numpy_data, dtype=torch.float32)

# Normalizace pomocí min-max škálování
min_vals = tensor_data.min(dim=0, keepdim=True).values
max_vals = tensor_data.max(dim=0, keepdim=True).values
normalized_tensor = (tensor_data - min_vals) / (max_vals - min_vals)

# Normalizace pomocí z-score škálování
mean_vals = tensor_data.mean(dim=0, keepdim=True)
std_vals = tensor_data.std(dim=0, keepdim=True)
zscore_tensor = (tensor_data - mean_vals) / std_vals

# Výstup
print("Původní tensor:")
print(tensor_data)
print("\nMin-Max normalizovaný tensor:")
print(normalized_tensor)
print("\nZ-Score normalizovaný tensor:")
print(zscore_tensor)


Původní tensor:
tensor([[ 10.,   5., 100.],
        [ 20.,  15., 200.],
        [ 30.,  25., 300.],
        [ 40.,  35., 400.],
        [ 50.,  45., 500.]])

Min-Max normalizovaný tensor:
tensor([[0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500],
        [0.5000, 0.5000, 0.5000],
        [0.7500, 0.7500, 0.7500],
        [1.0000, 1.0000, 1.0000]])

Z-Score normalizovaný tensor:
tensor([[-1.2649, -1.2649, -1.2649],
        [-0.6325, -0.6325, -0.6325],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.6325,  0.6325,  0.6325],
        [ 1.2649,  1.2649,  1.2649]])
